---
- name: Create Nginx build context
  file:
    path: "{{ deploy_path }}/nginx/conf"
    state: directory
    mode: '0755'

- name: Render Nginx Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ deploy_path }}/nginx/Dockerfile"
    mode: '0644'

- name: Render Nginx default config
  template:
    src: conf/default.conf.j2
    dest: "{{ deploy_path }}/nginx/conf/default.conf"
    mode: '0644'